name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Clone submodules
      run: git submodule update --init --recursive
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test app with Gradle
      run: ./gradlew sample:testDebug
    - name: Build debug APK with Gradle
      run: ./gradlew sample:packageDebug
    - name: Upload debug APK artifact
      uses: actions/upload-artifact@v4
      with:
         name: sample
         path: ./sample/build/outputs/apk/debug/*.apk
